os: linux
dist: precise 
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine
language: node_js
node_js: 8.0.0
yarn: 1.7.0
