os: 
  - linux
  - osx
osx_image: xcode9.3
language: node_js
yarn: 1.7.0
node_js: 8.0.0
go: 1.10.0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wine; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq wine; fi
install:
  - travis_wait yarn --link-duplicates --production
after_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 15 yarn build-mac; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 15 yarn build-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 20 yarn build-win; fi
