os: 
  - linux
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=\"$HOME/.yarn/bin:$PATH\"
  - sudo apt-get update -qq
  - sudo apt-get inistall -qq wine
language: node_js
node_js: 
  - 8.0.0
yarn: 
  - 1.7.0
