os: osx
osx_image: xcode9.3
language: node_js
yarn: 1.7.0
node_js: 8.0.0
go: 1.10.0
before_script:
- brew install wine
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn --link-duplicates
script:
- travis_wait 10 yarn build-win
- travis_wait 10 yarn build-lin
- travis_wait 10 yarn build-min
after_success:
- echo '√'
