os: osx
language: node_js
node_js:
- '8.0.0'
yarn:
- '1.7.0'
jobs:
  include:
    - script: echo "Setup"
      - brew install wine
      - npm install yarn --global
      - git config credential.helper "strore --file=.git/credentials"
      - echo "https://${GH_TOKEN}":@github.com" > .git/credentials
      - git checkout -b "v1.5.0-${TRAVIS_BUILD_NUMBER}"
      - yarn build-lin
    - script: echo "Building for Mac OSX"
      - yarn
      - yarn build-mac
    - script: echo "Building for Windows"
        - yarn
      - yarn build-win
    - script:
      - echo "Pushing back to github."
      - git add dist/*
      - git commit -am "Build ${TRAVIS_BUILD_NUMBER}"
      - git push origin "v1.5.0-${TRAVIS_BUILD_NUMBER}"
      on:
        tags: true
        repo: etaletai13/desktop
        branches:
          only: staging
